#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 24 16:50:15 2019

@author: sowjanyamattaparthi
"""
#Load the librarys
import pandas as pd #To work with dataset
import numpy as np #Math library
import seaborn as sns #Graph library that use matplot in background
import matplotlib.pyplot as plt #to plot some parameters in seaborn

# Importing the dataset
dataset = pd.read_csv('credit.csv')

dataset.head() #top 5 rows of the dataset

#Information about the data
dataset.info()
# No of observations and attributes
dataset.shape

# Summary of descriptive statistics
dataset.describe()

#Listing out names of columns
column_names=dataset.columns.tolist()

#How much the amount varies.
import matplotlib.pyplot as plt

num_bins = 10
plt.hist(dataset['credit_amount'], num_bins, normed=1, facecolor='blue', alpha=0.7)
plt.show()

#BUILDING A MODEL
#Looking unique values
print(df_credit.nunique())
#Looking the data
print(df_credit.head())

